import { promises as fs } from "node:fs";
import path from "node:path";
import process from "node:process";

const root = process.cwd();
const roots = ["docs", "examples", "templates"];
const sourcePaths = ["README.md", "CONTRIBUTING.md"];

async function walk(directory) {
  const entries = await fs.readdir(path.join(root, directory), { withFileTypes: true });
  const files = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name, "en"))) {
    const relative = path.posix.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await walk(relative));
    else if (entry.name.endsWith(".md")) files.push(relative);
  }
  return files;
}

for (const directory of roots) sourcePaths.push(...await walk(directory));
sourcePaths.sort((a, b) => a.localeCompare(b, "en"));

function groupFor(file) {
  if (file === "README.md" || file === "CONTRIBUTING.md") return "저장소 안내";
  if (file.startsWith("docs/00-")) return "처음 이해하기";
  if (file.startsWith("docs/10-")) return "기반 다지기";
  if (file.startsWith("docs/20-")) return "워크플로";
  if (file.startsWith("docs/30-")) return "도구";
  if (file.startsWith("docs/90-")) return "평가";
  if (file.startsWith("examples/")) return "예시";
  if (file.startsWith("templates/")) return "템플릿";
  return "문서 지도";
}

function headings(raw) {
  const result = [];
  let fenced = false;
  for (const line of raw.replace(/\r\n?/g, "\n").split("\n")) {
    if (/^```/.test(line)) { fenced = !fenced; continue; }
    if (fenced) continue;
    const match = line.match(/^(#{1,6})\s+(.+?)\s*#*$/);
    if (match) result.push({ level: match[1].length, text: match[2].replace(/[*_`]/g, "") });
  }
  return result;
}

const docs = [];
for (const file of sourcePaths) {
  const raw = await fs.readFile(path.join(root, file), "utf8");
  const found = headings(raw);
  docs.push({ path: file, group: groupFor(file), title: found[0]?.text || path.basename(file), raw });
}

const payload = `/* Generated by scripts/build-site.mjs. Markdown remains authoritative. */\nwindow.DOCS=${JSON.stringify(docs)};\n`;
await fs.writeFile(path.join(root, "site-content.js"), payload);

const manifest = docs.map((doc) => ({
  path: doc.path,
  bytes: Buffer.byteLength(doc.raw),
  headings: headings(doc.raw)
}));
await fs.writeFile(path.join(root, "site-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);

const list = docs.map((doc) => `        <li><a href="${doc.path}">${doc.path}</a></li>`).join("\n");
const indexPath = path.join(root, "index.html");
const index = await fs.readFile(indexPath, "utf8");
if (!index.includes("<!-- SOURCE_MAP_START -->") || !index.includes("<!-- SOURCE_MAP_END -->")) throw new Error("source map markers not found");
const next = index.replace(/(?<=<!-- SOURCE_MAP_START -->)\n[\s\S]*?\n(?=\s*<!-- SOURCE_MAP_END -->)/, `\n${list}\n`);
await fs.writeFile(indexPath, next);

console.log(`Built ${docs.length} documents into site-content.js`);
